import{S as u,i}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const f="21675808-1204a02bf0a9f212ef3ae3caa",d="https://pixabay.com";function p(s){const e={key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"},o=new URLSearchParams(e);return fetch(`${d}/api/?${o}`).then(a=>{if(!a.ok)throw new Error("Ups... The word is wrong!");return a.json()})}function m(s){return s.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href="${e.largeImageURL}">
                  <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
                </a>
                <div class="stats">
                  <p class="text">Likes<br/>${e.likes}</p>
                  <p class="text">Views<br/>${e.views}</p>
                  <p class="text">Comments<br/>${e.comments}</p>
                  <p class="text">Downloads<br/>${e.downloads}</p>
                </div>
              </li>`).join("")}const y=document.querySelector(".form"),l=document.querySelector(".gallery"),c=document.querySelector(".loader");y.addEventListener("submit",g);const h=new u(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});function g(s){s.preventDefault(),L(),l.innerHTML="";const e=s.target.queryInput.value.trim();e!==""?p(e).then(o=>{if(console.log(o),o.hits.length===0)return i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});l.innerHTML=m(o.hits),h.refresh()}).catch(o=>{console.log(o)}).finally(()=>{b()}):i.error({message:'Please, enter a query, for example "cats"',position:"topRight"}),s.currentTarget.reset()}function L(){c.classList.remove("is-hidden")}function b(){c.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
